import {
    NueAside,
    NueAvatar,
    NueBadge,
    NueBreadcrumb,
    NueBreadcrumbItem,
    NueButton,
    NueButtonGroup,
    NueCheckbox,
    NueCheckboxGroup,
    NueCollapse,
    NueCollapseItem,
    NueContainer,
    NueDialog,
    NueDiv,
    NueDivider,
    NueDrawer,
    NueDropdown,
    NueEmpty,
    NueFooter,
    NueHeader,
    NueIcon,
    NueInfiniteScroll,
    NueInput,
    NueLink,
    NueMain,
    NueMarquee,
    NueMessageWrapper,
    NuePopupPool,
    NueProgress,
    NueSelect,
    NueSelectOption,
    NueSwitch,
    NueText,
    NueTextarea,
    NueTooltip
} from '@nue-ui/components';

import type { Plugin } from 'vue';

export default [
    NueAside,
    NueAvatar,
    NueBadge,
    NueBreadcrumb,
    NueBreadcrumbItem,
    NueButton,
    NueButtonGroup,
    NueCheckbox,
    NueCheckboxGroup,
    NueCollapse,
    NueCollapseItem,
    NueContainer,
    NueDialog,
    NueDiv,
    NueDivider,
    NueDrawer,
    NueDropdown,
    NueEmpty,
    NueFooter,
    NueHeader,
    NueIcon,
    NueInfiniteScroll,
    NueInput,
    NueLink,
    NueMain,
    NueMarquee,
    NueMessageWrapper,
    NuePopupPool,
    NueProgress,
    NueSelect,
    NueSelectOption,
    NueSwitch,
    NueText,
    NueTextarea,
    NueTooltip
] as Plugin[];
