import {
    NueAvatar,
    NueBadge,
    NueButton,
    NueButtonGroup,
    NueCollapse,
    NueCollapseItem,
    NueContainer,
    NueDialog,
    NueDiv,
    NueDivider,
    NueDrawer,
    NueDropdown,
    NueFooter,
    NueHeader,
    NueIcon,
    NueInfiniteScroll,
    NueInput,
    NueLink,
    NueMain,
    NueMessageWrapper,
    NuePopupWrapper,
    NueText,
    NueTextarea,
} from "@nue-ui/components";

import type { Plugin } from "vue";

export default [
    NueAvatar,
    NueBadge,
    NueButton,
    NueButtonGroup,
    NueCollapse,
    NueCollapseItem,
    NueContainer,
    NueDialog,
    NueDiv,
    NueDivider,
    NueDrawer,
    NueDropdown,
    NueFooter,
    NueHeader,
    NueIcon,
    NueInfiniteScroll,
    NueInput,
    NueLink,
    NueMain,
    NueMessageWrapper,
    NuePopupWrapper,
    NueText,
    NueTextarea,
] as Plugin[];
